### ISSUE TITLE
services availablility

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#107]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adambreznicky](https://github.com/adambreznicky)**
_Monday Feb 25, 2019 at 18:12 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/107_

----

add a filter checkbox for datasets which are available as a service. under the 'Availability' section makes sense for this but that section is currently driven by the template so maybe a new, custom section is necessary to make this happen

**Comment by jwhaney** [comment]
closed via PR#221
