### ISSUE TITLE
Geography filter, download, and coverage map pitch & bearing tool

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#134]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwhaney](https://github.com/jwhaney)**
_Monday Mar 11, 2019 at 20:06 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/134_

----

add a tool tip or explanation of how to use the pitch and bearing (i think that's what it's called) tool. it's not obvious how to use which you have to hold control and then use the mouse or you can hold down the mouse on top of the tool. not very intuitive.

pitch and bearing tool icon:
![Screenshot from 2019-03-11 15-02-46.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b69c10b3c8a4500139e198f/125516c66e82c728ace21e0d46db978826878dba87e6ab03a24fff99691477227049f3783dd4b268ee1736515d424aaa53444d04bea6d37ef5f22e7a985958ecd06a5627c16940abe98a16bf00b2768e4e87beb9d85edcfa7f74b9dfd0126754505a9bf54f34a8934acd5df448e2495da715376ae3647b.png)

this tool exists in download map, coverage map, and the geography filter.

feedback from aubrey drescher on 3/11/19:
"I’m not sure what this button does on the map. Maybe add a tool tip to it."

**Comment by jwhaney** [comment]
i'm in favor of removing the pitch and bearing tool on all maps with an additional parameter when adding the navigation control:
`showCompass: false`

**Comment by jwhaney** [comment]
disabled nav compass in PR #239
