### ISSUE TITLE
Catalog cards available for download

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#137]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwhaney](https://github.com/jwhaney)**
_Monday Mar 11, 2019 at 20:17 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/137_

----

add a highlight, maybe an inset border, to the catalog cards that are available for download. or just change the filter option to 'Download' instead of 'Download and Order'.

feedback from aubrey drescher on 3/11/19:

"Consider highlighting the catalog cards which are available for download. Or, change the “Download and Order” filter option to “Download” (Since you’ve already got an “Order Only” option). I’d just like a quick way to see everything that’s downloadable from the website."

**Comment by jwhaney** [comment]
I believe this issue has been resolved with a previous unknown commit. The issue was resolved with just having "Download" as an Availability filter option instead of "Download and Order" which is what we used to have there.

Thoughts @adambreznicky & @JasonKleinert ??

**Comment by adambreznicky** [comment]
i vote "close it". it looks resolved to me.

**Comment by JasonKleinert** [comment]
I think we can close this. This specific issue was addressed by changing the filter option name.

**Comment by jwhaney** [comment]
cool, i thought so. thanks.
