### ISSUE TITLE
scroll to top button

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#159]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adambreznicky](https://github.com/adambreznicky)**
_Monday Mar 25, 2019 at 12:34 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/159_

----

in catalog view, if a user is scrolling down the card list, a button should appear in the bottom right corner after having scrolled a bit (1500px? or something of the like). i imagine it to be a circular floating action button (FAB) with an icon pointing to the top. when clicked, it scrolls back to the top of the list. 

one basic example here: https://www.lulus.com/categories/13/dresses.html

**Comment by jwhaney** [comment]
resolved with PR#206
