### ISSUE TITLE
Pricing Summary Revisions

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#169]
<a href="https://github.com/csidenblad"><img src="https://avatars2.githubusercontent.com/u/23489372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [csidenblad](https://github.com/csidenblad)**
_Wednesday Mar 27, 2019 at 18:44 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/169_

----

- [ ] Can we please revisit the language on this before publishing? 

Historical search (1 image per decade): $40.00 per site
Historical Imagery cost: ‘1 image per decade’? What exact does this mean? And ‘per site’? Does that mean if someone sends a shapefile with multiple locations that I should be charging per individual feature in the AOI?

**Comment by adambreznicky** [comment]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwhaney](https://github.com/jwhaney)**
_Thursday Mar 28, 2019 at 13:39 GMT_

----

reference issue #37

**Comment by adambreznicky** [comment]
<a href="https://github.com/ThorTheDestroyer"><img src="https://avatars1.githubusercontent.com/u/8398036?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThorTheDestroyer](https://github.com/ThorTheDestroyer)**
_Thursday Mar 28, 2019 at 14:13 GMT_

----

@csidenblad @LaurenKirk Good point! Lets change it to this. 

## Historical Imagery Reproduction Costs

- Full historical search : $40.00 per site 
- Single year historical search: $18.00 per site
   -   Standard historical searches are delivered on 8 1/2" x 11" laser copies(1 image per decade for full historical)
- Scanned historical frame: $10.00 per image
- Scanned + georeferenced historical frame: $20.00 per image
- Digital download (0 - 10GB): $7.00


Is that a better explanation?

**Comment by adambreznicky** [comment]
<a href="https://github.com/csidenblad"><img src="https://avatars2.githubusercontent.com/u/23489372?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [csidenblad](https://github.com/csidenblad)**
_Thursday Mar 28, 2019 at 14:34 GMT_

----

@ThorTheDestroyer @LaurenKirk 
Yes, that is better. Can we keep "1 image per decade" with the Multi-year search?

•   Multiple year search (1 image per decade): $40.00 per site
•   Single year search: $18.00 per site 
•   Scanned historical frame: $10.00 per image
           - Historical searches are delivered on 8 1/2" x 11" laser copies if paper copy is requested
•   Scanned + georeferenced historical frame: $20.00 per image
•   Digital download (0 - 10GB): $7.00

**Comment by adambreznicky** [comment]
<a href="https://github.com/csidenblad"><img src="https://avatars2.githubusercontent.com/u/23489372?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [csidenblad](https://github.com/csidenblad)**
_Thursday Mar 28, 2019 at 14:36 GMT_

----

@ThorTheDestroyer @LaurenKirk
Or maybe "1 image per collection"?

**Comment by adambreznicky** [comment]
<a href="https://github.com/LaurenKirk"><img src="https://avatars1.githubusercontent.com/u/31768897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LaurenKirk](https://github.com/LaurenKirk)**
_Thursday Mar 28, 2019 at 14:41 GMT_

----

@ThorTheDestroyer @csidenblad 

Correct me if i'm wrong but could we do something like this:

**Research fee:**
• Multiple year search (1 image per decade): $40.00 per site
• Single year search: $18.00 per site
--------------------------------------------------------------------
**Additional fees:**
• Scanned historical frame: $10.00 per image
- Historical searches are delivered on 8 1/2" x 11" laser copies if paper copy is requested
• Scanned + georeferenced historical frame: $20.00 per image
• Digital download (0 - 10GB): $7.00

We are going to charge a customer their base research fee regardless.  The digital download, georeferencing, and scanning fees should be shown as add-ons to an order no?

**Comment by adambreznicky** [comment]
<a href="https://github.com/LaurenKirk"><img src="https://avatars1.githubusercontent.com/u/31768897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LaurenKirk](https://github.com/LaurenKirk)**
_Thursday Mar 28, 2019 at 14:41 GMT_

----

dont know why that whole top section became bold.  only meant to bold the "research fee" title

**Comment by adambreznicky** [comment]
<a href="https://github.com/LaurenKirk"><img src="https://avatars1.githubusercontent.com/u/31768897?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [LaurenKirk](https://github.com/LaurenKirk)**
_Thursday Mar 28, 2019 at 14:42 GMT_

----

Research Fees: 
• Multiple year search (1 image per decade): $40.00 per site
• Single year search: $18.00 per site
--------------------------------------------------------------------------
Additional Fees:
• Scanned historical frame: $10.00 per image
- Historical searches are delivered on 8 1/2" x 11" laser copies if paper copy is requested
• Scanned + georeferenced historical frame: $20.00 per image
• Digital download (0 - 10GB): $7.00

**Comment by adambreznicky** [comment]
<a href="https://github.com/ThorTheDestroyer"><img src="https://avatars1.githubusercontent.com/u/8398036?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThorTheDestroyer](https://github.com/ThorTheDestroyer)**
_Thursday Mar 28, 2019 at 14:48 GMT_

----

well if they want digital, then 1 image per decade is misleading. stating that it is 1 image per decade for paper copies is the rule. it doesn't apply to digital.

**Comment by jwhaney** [comment]
has this issue been resolved @csidenblad, @LaurenKirk ???? just trying to go through and clean up some old issues here.

**Comment by ThorTheDestroyer** [comment]
@csidenblad @LaurenKirk since you are revisiting this, it might be a good time to consider the new historical search pricing I worked up and proposed to you a while back.  New pricing definitely recovers costs better than the old model since the workflow for searches has changed with the archive updates you have done.

**Comment by jwhaney** [comment]
bump. this has gone pretty stale. 
@csidenblad @LaurenKirk

**Comment by jwhaney** [comment]
:cricket: :cricket: :cricket: ....... i'm just gonna go ahead and close this now......

:no_mouth:
