### ISSUE TITLE
Historical imagery collections datahub metadata additions

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#171]
<a href="https://github.com/ThorTheDestroyer"><img src="https://avatars1.githubusercontent.com/u/8398036?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ThorTheDestroyer](https://github.com/ThorTheDestroyer)**
_Thursday Mar 28, 2019 at 14:18 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/171_

----

@adambreznicky 

- [ ] add to and from date(under the heading coverage dates) to metadata section of historical imagery datasets in the data hub
- [ ] add collection/mission(under heading collection mission number) to metadata section of historical imagery datasets  in the data hub

Feel free to name the heading something else if you think of anything that will read better.

**Comment by adambreznicky** [comment]
@LaurenKirk @christoball this issue is from a year ago. what is the current opinion of RDC regarding this request? do we want to move forward with either, both, or none of these metadata additions?

**Comment by LaurenKirk** [comment]
@adambreznicky @christoball 
I would advocate not including the to from date.  Could cause confusion for users who aren't familiar with all the quirks of the archive.

I have no problem with moving forward on the second option of adding the collection/mission number to its metadata section.  May be helpful for users who are downloading multiple collections at one time and need to easily distinguish files.

**Comment by christoball** [comment]
@adambreznicky @LaurenKirk let me know if any action is needed on my part. Is there any styling on the front-end that needs to be considered?

**Comment by adambreznicky** [comment]
sorry, got my @ mentions messed up

@christoball styling shouldn't be an issue, it will be just another item on the metadata list and styled the same as the rest. 

@csidenblad see above; thoughts?

**Comment by csidenblad** [comment]
@adambreznicky  I agree with Lauren about adding the mission number (although not truly a number data type, some agencies use alpha to designate mission) to the collections' metadata. 

@LaurenKirk I think we should consider adding the to-from date to the collections. This was something previously and briefly discussed, referring specifically to TXDOT collections that may cover multiple counties over multiple years. Consider this example b50fc728-97f7-428d-b459-942b02a4199b Multicounty TXDOT collection ranging from 1984 to 1989. I can see how it might lead to some confusion in requests, but I also think providing the info helps them make a better decision if they think that collection will suit their project needs or not. Let me know what you think. 

Also, when adding missions numbers, will we want to revisit USDA collections to update those that are listed with a 3-Alpha code when they are truly represented by fips code?

**Comment by adambreznicky** [comment]
resolved 500e3e98fe42031c5df2ffd08b52ab66124a1390
added mission number to metadata.
skipping the addition of from/to dates in metadata. to date already represented in collection card title. inserting additional dates will most likely cause more user experience issues than it solves (too many dates, too many questions).
