### ISSUE TITLE
geography filter geocoder

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#18]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adambreznicky](https://github.com/adambreznicky)**
_Friday Jan 11, 2019 at 15:34 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/18_

----

add a geocoder search option within the geography filter dialog/map to help users find their desired map location faster.

**Comment by JasonKleinert** [comment]
Closed with release v1.7.0, and commit 5b0663d92b18d377248ebf71e6e9952c11791b87
