### ISSUE TITLE
County Names listed in Scanned Indexes 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/dataHub#189]
@mitchellryant @JasonKleinert @adambreznicky @jwhaney 

Please include County Names Index Sheets list on collection details page. Currently unable to identify which sheets belong to which county in Multi County Collections. Image below is from https://data.tnris.org/collection/e2dcaed5-11ae-4792-8b18-430952ff6b7f
![image](https://user-images.githubusercontent.com/23489372/58661230-f375ff00-82ec-11e9-8775-3994ee0aa445.png)

This list shows 2 Brazoria Indexes and 1 for Harris, but user is unable to determine which sheet 1 they would be downloading.

**Comment by jwhaney** [comment]
@csidenblad, so i've found some variations in the link url structure. this causes problems when i'm trying to grab that county name every time from the same position in the url string. see below:

historical collection id: __19dc984f-f7ad-4c9a-9e45-6e3f9cff2f4b__
position of county name in url string array: __4__
beginning of url before county name: __https://tnris-ls4.s3.amazonaws.com/bw/COUNTY__

VS

historical collection id: __8d910c96-c442-4f7b-89cb-0e5fa89a9b96__
position of county name in url string array: __5__
beginning of url before county name: __https://s3.amazonaws.com/tnris-ls4/bw/COUNTY__

seems like some collections do not have the __tnris-ls4__ directory in the url string??? i'm not sure if this is just a mistake or something else and i do not know the extent of it, meaning there could be other variations. maybe @adambreznicky can provide some additional info? it would be much appreciated.

**Comment by adambreznicky** [comment]
both urls are correct. 
https://stackoverflow.com/questions/25191041/is-there-any-difference-on-the-url-you-use-to-amazon-s3-files

@csidenblad FYI - when loading in cloudberry to s3, aws automatically created 3 different urls for uploaded object. their structure is different, and one permits different protocols, but they all work and are all correct. insofar as the directions y'all were given, you did it correctly. insofar as data integrity, they should all choose the same structure. 

i'm going to bulk upload them in the database today to use the same structure. that should fix the data integrity and reduce @jwhaney need to write special logic handling. all will be well!

i'm on it right now...

**Comment by adambreznicky** [comment]
okee dokee, bulk update done. total 5668 ls4 scanned index links are all now using the "https://s3.amazonaws.com/tnris-ls4/bw/COUNTY" structure.

**Comment by jwhaney** [comment]
¡Muchas gracias!

**Comment by jwhaney** [comment]
closed via PR #245
