### ISSUE TITLE
Search bar not working in MS Edge browser

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/dataHub#193]
Search bar is inactive in edge browser.

**Comment by jwhaney** [comment]
as of latest version of Edge (windows virtual machine) on browserstack (v18), the search bar seems to work fine. i'll keep testing to try and reproduce this bug with the latest version of edge. seems like if edge switched to a Chromium base, we may not have this issue anymore.

**Comment by jwhaney** [comment]
closing this as the app search bar works on latest version of edge and with the eventual migration of everyone over to the chromium based version of edge, this problem will fix itself.
