### ISSUE TITLE
New Style

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#195]
![Landing](https://user-images.githubusercontent.com/8459928/59303492-f0b7ca00-8c5b-11e9-8303-0f8ff319beb6.jpg)
![CatalogView](https://user-images.githubusercontent.com/8459928/59303500-f31a2400-8c5b-11e9-9f1c-51b4ddfdc241.jpg)
![MapView](https://user-images.githubusercontent.com/8459928/59303502-f4e3e780-8c5b-11e9-8c27-4db461170a3d.jpg)

**Comment by adambreznicky** [comment]
closing due to irrelevance
