### ISSUE TITLE
Partial Dataset Orders - replace spaces in file name in user uploads

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#198]
no spaces in uploads.

either rename file on upload or tell you there can no be spaces in the upload file name.

**Comment by jwhaney** [comment]
@mitchellryant, is this related to partial dataset orders? so when someone uploads a zipped shapefile or screenshot image?

**Comment by jwhaney** [comment]
after convo, clarification is that underscores need to replace spaces or spaces just removed. this is for any collection order form for partial orders which requires uploading a zipped shapefile or uploading a screenshot. got it.

**Comment by jwhaney** [comment]
closed via pull request #208
