### ISSUE TITLE
98 hypso - drop state downloads

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#228]
98 hypso collection: get rid of the statewide download as it duplicates the quad downloads. quad is the native extent for the downloads.

**Comment by jwhaney** [comment]
gonna close this cuz i think @mitchellryant and I knocked it out yesterday

**Comment by jwhaney** [comment]
re-opening because it this isn't quite resolved.

re-evaluating how this dataset is chopped up. might make sense to have a county level chop along with quad level, or maybe only the county level. right now the dataset is NON-Public so not available until we figure out how its gonna be chopped up.

**Comment by mitchellryant** [comment]
data has been chopped from complete statewide feature class into county shapefiles. statewide and quads resources have been removed. collection has been made public again.

**Comment by jwhaney** [comment]
:+1:
