### ISSUE TITLE
county dropdown to download maps

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#229]
add the county dropdown to the download maps:

- map loads to extent of available county coverage
- quads turn on at a county extent once a county is selected and zoomed to
- NAIP and TOP county dropdown supplies a link for CCM download, otherwise functionality is the same
- statewide datasets function as they do now, no dropdown for these

**Comment by JasonKleinert** [comment]
Closing this one because the county dropdown feature has been deprecated and replaced with the geocoder feature in release v1.7.0. This feature has been added to the download maps.
