### ISSUE TITLE
add basemap switcher - default & imagery

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/dataHub#236]
add a basemap toggler/switcher for download map and also geo filter possibly. not really useful but guess we could add it to the coverage map as well.

just the carto voyager and texas imagery service is probably good. dont want too many basemap choices.

**Comment by jwhaney** [comment]
basemap seems to be working nicely, except for some NAIP collections. imagery layer doesn't seem to turn on for some naip's. no console errors. keep testing...

**Comment by jwhaney** [comment]
__update__: seems that collections with a download area control menu (multiple area types) is conflicting with the basemap switcher which works fine on all other collections.

**Comment by jwhaney** [comment]
update after discussion on 12/4 dev symposium. instead of texas imagery service, use a more generic imagery service like esri's world imagery. call the layer __satellite__. instead of calling the default base map layer 'voyager', use the label __streets__ or __default__ in the base map toggler radio input.

**Comment by jwhaney** [comment]
i like the term 'imagery' vs. 'satellite'. 'default' and 'imagery' radio button labels with NAIP 2018 as the imagery source.

**Comment by adambreznicky** [comment]
implementation via commit 30bb52cdb8cdf9aa29b822ae182e71a050a3de82

still to do:

- [ ] adjust download areas sass to lighten color when satellite on
- [ ] pull out download map layer chooser into separate component
- [ ] add basemap selector to hist aerial index download map
- [ ] add basemap selector to geofilter map
- [ ] add basemap selector to county coverage map? seems unnecessary
- [ ] pull out hist aerial index download layer selector into separate component

**Comment by adambreznicky** [comment]
sass colors for satellite completed via commit a1699717471a0c1af51568479b6642a1682df9c5

**Comment by adambreznicky** [comment]
download layers separated out into new LayerSelector component via commit 8b8d18d1f5e8a2cc00890fdd290b34a4c0431349

**Comment by adambreznicky** [comment]
added basemap selector to hist aerial index download map via commit 2b0326042d9c80e096149655fa89285205209f6f

**Comment by adambreznicky** [comment]
migrated index download layer selector into new component via commit 0104c7104079bba7962ce25014ae05c427482311

**Comment by adambreznicky** [comment]
- [ ] zoom out still appears disabled after switching away from qquad (naip + top) to another layer when the zoom restriction changed. button is simply not updated when map is, until a mouse scroll occurs and the button recognizes the change in the map

**Comment by adambreznicky** [comment]
updated zoom nav control restrictions after resetting min zoom on layer change. resolved via commit c79b51eae0c5c4ce6bec169c01262bd83ffafa8f

**Comment by adambreznicky** [comment]
despite consistency, i'm optioning to not add the basemap selector to the county coverage map. although technically interactive, this map is closer to an image than an interactive tool for users. it's a visual quick reference of non-specific and non-accurate symbolism so promoting interaction will only encourage users to mis-understand the non-accurate information portrayed in the quick reference map component (would be deviant of this component's purpose).

**Comment by adambreznicky** [comment]
last to do point listed above, "migrate functionality of adding download layers in map over into separated layer selector component", is a large reconfiguration change and beyond the scope of this issue. all other points outlined, and the original request, for this issue have been satisfying so i'm closing this one and creating a new issue for the last to do.
