### ISSUE TITLE
Add Header to Lidar note

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#243]
please a header to the lidar note.

ideas.
Lidar Disclaimer
Lidar Note
About Lidar Downloads

**Comment by jwhaney** [comment]
let me know your thoughts on this @mitchellryant ??

![image](https://user-images.githubusercontent.com/13525011/71994927-3f800f00-31ff-11ea-83d6-d75288453207.png)

**Comment by mitchellryant** [comment]
looks great.
![MNeE7](https://user-images.githubusercontent.com/8459928/71996946-be2a7b80-3202-11ea-99f8-53c47f1a0433.jpg)

**Comment by jwhaney** [comment]
gracias!

**Comment by jwhaney** [comment]
closed via PR #244
