### ISSUE TITLE
Historical Imagery collections "Scanned" Badge added to Metadata. 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/dataHub#247]
@adambreznicky 
Please add a badge to Historical collections where the field for "Fully Scanned" is equal to TRUE. Please add the badge as the last line of the metadata. 

![scannedbadge](https://user-images.githubusercontent.com/23489372/73381589-a12a1b00-428b-11ea-9b7f-0d7ce4d5202e.png)

We are not particular about what badge is used, but have provided a few examples of images we liked. 
![examples](https://user-images.githubusercontent.com/23489372/73382517-47c2eb80-428d-11ea-848a-54f9a0d41240.png)

Also curious to see how difficult it might be to place the badge on the collection card itself. 
![scannedcollection](https://user-images.githubusercontent.com/23489372/73382028-67a5df80-428c-11ea-8921-359e31948d20.png)

Please let us know what y'all think and what else the RDC can do to help make this dream a reality. Thank you!

**Comment by adambreznicky** [comment]
awesome! thanks for the examples and detailed suggestion.
we use google's Material for our ui framework so they might have some similar out-of-the-box badges we could look at using. if so, they would probably be built with css opposed to being an image, so they would be responsive and scalable. we'll have to see and play with it though to see what the complete list of options are.
thanks again

**Comment by adambreznicky** [comment]
resolved fb5787ec2ac1624a3990850d132d94cc4e7709d8
