### ISSUE TITLE
RDC Pricing Updates for DataHub Checkout Page

### ISSUE THREAD

**Issue by LaurenKirk** [TNRIS/dataHub#252]
@csidenblad @adambreznicky @mitchellryant 

Howdy, effective March 2nd the public pricing on TNRIS.org will update. Can you please add the following updates to the checkout page on DataHub? Format can look exactly the same as it is currently.

Research:
$60/ Full Historical Search (multiple years or sites)
$30/Single Year Search (one site and one year)
$15/Frame Search (customer must be able to identify specific frames needed)

Imagery:
$10/frame
$20/georeferenced frame (all frames will be georeferenced to WGS 1984)

Delivery Options:
$7 digital download delivery (0-10gb)

Bulk Collection Delivery Option

Customers have the option of ordering any collection that has already been scanned in full for the data size price (see Data Reproduction Costs), rather than paying by frame.

Delivery Policy:

TNRIS requests 3-10 business days for data requests and product turn around. We do not accommodate any expedited orders.

**Comment by csidenblad** [comment]
thank you for discussing the formatting prior to pushing to the site. The following screen shot is how the RDC would like to see the section formatted. I will be adding to datahub issue as well. Let me know if you still have questions. Thank you. 

![image](https://user-images.githubusercontent.com/23489372/75783776-b7ae1100-5d26-11ea-98db-173db5c285c8.png)

**Comment by adambreznicky** [comment]
@csidenblad @LaurenKirk got it, thanks! i started working on this update, will have it completed as soon as possible. getting it done in between training sessions. appreciate it
