### ISSUE TITLE
Update or replace react-responsive-carousel 

### ISSUE THREAD

**Issue by JasonKleinert** [TNRIS/dataHub#257]
React is deprecating the lifecycle method `componentWillReceiveProps` as "unsafe" in v17. This package utilizes this method in it's 2 source files. We will need to find an alternative or update the package if the owner of the project does not. The image carousel will likely break when we update to React v17. Just something to keep on our roadmap.

**Comment by adambreznicky** [comment]
looks like there is a PR on the source code awaiting approval/merging which will resolve this issue
https://github.com/leandrowd/react-responsive-carousel/pull/394

let's check back in on the PR in a bit, hopefully the owner resolves it quickly

**Comment by adambreznicky** [comment]
updated package via commit 8564e50948eea468cd7ba7ad297d2c20b0fb0d45
PR was merged and released for package fixing this issue for the Carousel component within the package. Was not fixed for the Thumb component within the package though... 

going to leave this open and circle back again to check the Thumb component in the future. for now, disabling the thumbnails option in our implementation of the carousel solves this issue from our end but at the sacrifice of the thumbnails. leaving thumbnails still enabled for now, can disable if we update react and run into problems.

https://github.com/leandrowd/react-responsive-carousel/issues/418

**Comment by adambreznicky** [comment]
package source was updated.
new version updated in our package.json.
resolved d5446b3beb7385206a1b4539ef9c421b53cbe11f
