### ISSUE TITLE
shopping cart - order submission messages

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/dataHub#259]
after successfully submitting an order from the shopping cart, the user is provided two messages. the Success! message for successfully ordering a dataset, AND a message saying that there are no datasets in your cart. 

maybe we need to only show the Success! message and prevent the no datasets in your cart message from showing if a dataset was just ordered? just an idea.

![Screenshot from 2020-03-18 15-25-00](https://user-images.githubusercontent.com/13525011/77005189-64df7680-692e-11ea-8240-af4118066b9e.png)

**Comment by JasonKleinert** [comment]
I think that is a good idea. I was focused only on the React code refactor today, but I think that would be a nice change.

**Comment by adambreznicky** [comment]
resolved 7ff562483da18903d0199e1955abe490a12cb69b
