### ISSUE TITLE
TCEQ Open Data Portal

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#261]
I added the link to their source page. Is there a way to give them the TxDOT treatment?

 https://gis-tceq.opendata.arcgis.com

**Comment by adambreznicky** [comment]
automated task runs daily to retrieve their services (txdot treatment). pretty sure all you have to do is populate their open data group id in the admin console and the process will pick it up

**Comment by mitchellryant** [comment]
what is that id?

**Comment by adambreznicky** [comment]
group id finder
https://developers.arcgis.com/javascript/3/samples/portal_getgroupamd/
searching "txdot open data" revealed the group code we have in our database


using it to search for "tcewq open data" returned a single result:
01627bf7da784a64a2f5974bbe7dac02

you could email them to confirm that is it.

**Comment by mitchellryant** [comment]
Ill have to contact TCEQ for their ArcGIS Online Open Data Portal 'Group ID'. 

There is not dev work need to give them the TxDOT treatment, closing issue.
