### ISSUE TITLE
Add option for "No single frames available' to scan status of frames 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/dataHub#262]
I would like to list in the metadata collections that are photo index only, meaning that no individual frames for this collection are available for download or order. Adam had suggested that it could possibly be added to the newest metadata field 'Scan Status of Frames' with options being: Complete, In Progress, and No Single Frames Available. 
Let me know if you need any more info. 
Thank you!!
@adambreznicky @LaurenKirk

**Comment by LaurenKirk** [comment]
@csidenblad Sounds great to me!

**Comment by adambreznicky** [comment]
resolved a6dd3c78252520547a492c5d32ffb39395726a41
