### ISSUE TITLE
collections with no resources or issues with the resources

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/dataHub#268]
@adambreznicky provided a hotfix on 4/24 so the collection details page doesn't throw a bunch of console errors and there is actual content shown to the user saying there was an issue and to contact tnris about the problem. this is for collections that potentially have no resources for some reason or have a problem with the resources.

**this issue points out a need to maintain the new error message about the problem with the collection resources, regardless if the user switches tabs.** 

right now if the user moves to the contact or images tab or whatever, then goes back to the details page, the error message is gone and there is a placeholder empty download map. maybe it is related to the component updating? not sure but just documenting it here.

**Comment by adambreznicky** [comment]
def was related to the component updating. no resources text relied on response from resources api endpoint returning which doesn't happen 'again' between switching tabs, resources are already retrieved at that point.

resolved via commit afd912162ea78c196335e7671a84ae2b1f28601f
