### ISSUE TITLE
Web Service's Link

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#275]
The Online Mapping Service Note will need to change. Im updating the WMS and Preview links in the API as services are published. it is a work in progress, I hope to complete end of Aug or Mid Sept. The link will need to be changed to https://imagery.tnris.org/server/rest/services/.

To further complicate things Imagery and Feature Services are split on different AGS boxes,  So the note for Feature based services will be https://feature.tnris.org/arcgis/rest/services. I do not recall if there is way to really determine this via code.

I will update this ticket upon completion of my task.

![Services](https://user-images.githubusercontent.com/8459928/89210338-8eb7d380-d585-11ea-8165-4131c79acde8.PNG)

**Comment by mitchellryant** [comment]
possibly may need a note to let users know old links will be dying.

**Comment by mitchellryant** [comment]
i think this change will affect the preview in the maps.

**Comment by JasonKleinert** [comment]
@mitchellryant I think you're right
