### ISSUE TITLE
Improve user access to Shopping Cart once an item has been ordered from collection view (UX)

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/dataHub#280]
there have been some tickets come in related to users having issues accessing the shopping cart after they order from the collection view. this is has been a known UX issue for sometime and i think we all agree it should be improved.

@mitchellryant can you provide a number of tickets that have come in related to this issue since we launched? last year? 6months? i've logged links below to your and others comments from the other issue for reference.

reference information and ideas from issue #278:
https://github.com/TNRIS/dataHub/issues/278#issuecomment-693593119
https://github.com/TNRIS/dataHub/issues/278#issuecomment-694181029
https://github.com/TNRIS/dataHub/issues/278#issuecomment-694209416
https://github.com/TNRIS/dataHub/issues/278#issuecomment-694237779
https://github.com/TNRIS/dataHub/issues/278#issuecomment-694238328
https://github.com/TNRIS/dataHub/issues/278#issuecomment-694240537

**Comment by ctrepka** [comment]
Could we conditionally render the search bar in the navigation bar based on the current URL path? This would keep the shopping cart button visible at all times, and would also keep the 'DataHub' branding up top as well. 

Currently, the only global navigation bar on the site links to TNRIS.org and TWDB's website, but none to the homepage of the actual website the user is on. This is an additional UX issue, but can be solved at the same time by keeping a secondary navigation bar at the top with the shopping cart link and 'DataHub' linking to data.tnris.org.

**Comment by mitchellryant** [comment]
An exact number be hard to come up with. Most of this tickets went directly to the Data or Category Owner. I would need to discuss this with CS when she returns. There might be a number of phone calls.

**Comment by jwhaney** [comment]
> An exact number be hard to come up with. Most of this tickets went directly to the Data or Category Owner. I would need to discuss this with CS when she returns. There might be a number of phone calls.

Ya i figured it might be tough to get an exact number. I guess just an approximate or educated guess might be useful. It was just an idea to maybe get a grasp up front how serious this issue is for users. Regardless, I think its something we should fix for sure.

**Comment by mitchellryant** [comment]
Could we just close the collection card after the user adds it to card? returning the user to beginning or their search.

**Comment by jwhaney** [comment]
the absolute quickest/easiest fix is to provide a link in the message that appears after a user orders the collection. that button or link would send them to the shopping cart. however, i'm not convinced that the quickest/easiest route is best here. the goal is to largely improve the user experience and that isn't necessarily limited to just this issue. if it makes sense to reconfigure components or move them around, then i'm all for that.

> Could we conditionally render the search bar in the navigation bar based on the current URL path? This would keep the shopping cart button visible at all times, and would also keep the 'DataHub' branding up top as well.
> 
> Currently, the only global navigation bar on the site links to TNRIS.org and TWDB's website, but none to data.tnris.org. I think this is an additional UX issue, but can be solved at the same time by keeping a secondary navigation bar at the top with the shopping cart link and 'DataHub' linking to data.tnris.org.

Chris, I'm not sure I completely understand this idea, but I get the gist and this is one of those larger UI/UX changes that will likely make a bigger more positive difference. We should probably all get together soon to talk about ideas and to nail down a plan. I believe @Ldsmiths has already been working on putting together some slides regarding datahub UX issues as well as ideas for solutions. These slides could be the center point of our upcoming conversation.

**Comment by Ldsmiths** [comment]
> the absolute quickest/easiest fix is to provide a link in the message that appears after a user orders the collection. that button or link would send them to the shopping cart. however, i'm not convinced that the quickest/easiest route is best here. the goal is to largely improve the user experience and that isn't necessarily limited to just this issue. if it makes sense to reconfigure components or move them around, then i'm all for that.
> 
> > Could we conditionally render the search bar in the navigation bar based on the current URL path? This would keep the shopping cart button visible at all times, and would also keep the 'DataHub' branding up top as well.
> > Currently, the only global navigation bar on the site links to TNRIS.org and TWDB's website, but none to data.tnris.org. I think this is an additional UX issue, but can be solved at the same time by keeping a secondary navigation bar at the top with the shopping cart link and 'DataHub' linking to data.tnris.org.
> 
> Chris, I'm not sure I completely understand this idea, but I get the gist and this is one of those larger UI/UX changes that will likely make a bigger more positive difference. We should probably all get together soon to talk about ideas and to nail down a plan. I believe @Ldsmiths has already been working on putting together some slides regarding datahub UX issues as well as ideas for solutions. These slides could be the center point of our upcoming conversation.

Yeah, what Chris mentioned here was one of the first things I noticed. Navigating back to the DataHub home isn't as clear as it could be, which could be part of re-structuring the navigation bar as a whole to make the cart more visible as well. This is also something we would likely validate with user feedback.

**Comment by ctrepka** [comment]
Here's an image of what I had in mind, just as an example. It was a few one liners in header.js 
![image](https://user-images.githubusercontent.com/49252844/93627882-3d379c80-f9ab-11ea-8c4b-773e9b2b261b.png)

I think all of the solutions offered are great. If we could just hyperlink the 'visit the shopping cart' text to take the user to the shopping cart, in addition to having the cart linked at the top right, that would give the users a lot of opportunities and cues to navigate to the cart.

Looking forward to those slides!

**Comment by JasonKleinert** [comment]
I briefly mentioned in the issue about the site metrics that the datahub went through a serious redesign during it's initial development. It would be useful to share in a meeting the story of how we got to where we are and what the initial design was. Also would be good to share the ideas we have had as far as any major enhancements. A little understanding of the intended functionality could help with planning future enhancement.
