### ISSUE TITLE
Preview in Download Map not Working

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#282]
the preview in the download maps for new image services are not working. as new images service are created API is updated. WMS link in note is correct but Preview Map does not load. 

![282](https://user-images.githubusercontent.com/8459928/94447169-22191980-016f-11eb-9132-5e64fe76a4a8.PNG)

**Comment by mitchellryant** [comment]
https://webservices.tnris.org/arcgis/services/StratMap/StratMap09_CIR_6in_Galveston/ImageServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

**Comment by mitchellryant** [comment]
https://imagery.tnris.org/server/services/StratMap/StratMap09_CIR_6in_Galveston/ImageServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

**Comment by adambreznicky** [comment]
looks like the URLs were accidentally altered when entering them into the admin console. the smith 2020 example accidentally included "rest/" in the wms url which needs removal. the popupurl was missing a "/WMSServer" at the end before the jsapi query. fixing the URLs in the admin console resolves this issue
