### ISSUE TITLE
Popup Modal

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#285]
to help people understand OTLS (abstracts) and Topo Maps are note here naymore.

The OTLS, Digital Raster Graphics, and some other datasets have been removed based on data currentness and availability on other sites. TNRIS is always based on providing the users with the best most current versions of datasets. In doing that it my be necessary to have users jump to other data site.

[National Wetlands Inventory](https://data.tnris.org/collection/13145bca-1445-4890-af64-d834c171b7ec) - The NWI maps we had on the site were extremely dated, and it looks like US Fish and Wildlife does not produce the NWI maps anymore. You can get vector data directly from the [US Fish and Wildlife GIS data site](https://www.fws.gov/wetlands/Data/Data-Download.html). If you really just need the outdated maps, you can download them [here](http://cdn.tnris.org/data/national-wetland-inventory/national-wetland-inventory-24k.zip).

[Original Texas Land Surveys](https://data.tnris.org/catalog/%7B%22search%22%3A%22OTLS%22%7D) - There are 2 version of this data the GLO version, and the RRC version. The GLO version is licensed via a private company unavailable for distribution. The RRC version, the one that was on the site, is some what different, but it is nearly impossible to talk to anyone at RRC about issues related to the data. It is also on a varied update cycle and this update date is rarely given to TNRIS. Both GLO and RRC have map services with the OTLS in it. This services provide users access to the most current version of the data.

- A search for Original Texas Land Surveys or OTLS will return the agencies responsible for the dataset. That dataset collection is no longer available from TNRIS. You would need to contact RRC or GLO directly.

- The GLO version of the data can not be downloaded, but can be used in their [online map viewer](http://gisweb.glo.texas.gov/glomapjs/index.html).

- You should be able to get the most current version of the data from RRC, but i think you would have to order it. [RRC Map Viewer](https://rrc.texas.gov/about-us/resource-center/research/gis-viewers/)

[National Flood Hazard Layer](https://data.tnris.org/collection/55e56ffd-6ef3-4a41-a0fd-830719e9a936) - This dataset is is updated a frequency that we can not handle moving the data in and out of the system. This collection card has a link the FEMA Map Service Center where you can get the most up to date FEMA dataset.

[Digital Raster Graphics](https://data.tnris.org/collection/63dcfe92-41f1-49ed-887d-fc0ba460bea6) - (various scales of topo maps) - This dataset collection was removed due to currency of the data. The most current map we had was from the 1980s. The USGS has more current versions of the maps, in GeoPDF format, within the USGS collection card you can find a link to one of the site the USGS uses to distribute this data. If you really just need the outdated maps, you can download them [here](http://cdn.tnris.org/data/usgs-drg-classic/usgs-drg-collarless.zip).

[NRCS Soils](https://data.tnris.org/collection/50f2ae45-f465-46fb-a7be-2c56d88a380c) - The version of the soils that was on the TNRIS was created by a TNRIS staff member, and has been updated since 2010. The simplified version only contained 1/10 the information you can get from SURSGO. 

[TxDOT Urban files](https://data.tnris.org/collection/b1d85fd2-57ce-4bcb-8c21-954b06411e56) - These files are extremely dated. TxDOT has not update the files since 2003. The last set TNRIS got was from after that update. If you are looking for current roadway data, you should use the [TxDOT Open Data Portal](http://gis-txdot.opendata.arcgis.com/). From there you can view and export roadways and all the other layers managed by [Texas Department of Transportation](https://data.tnris.org/collection/b1d85fd2-57ce-4bcb-8c21-954b06411e56). If you really just need the outdated maps, you can download them [here](http://cdn.tnris.org/data/txdot-urban-files/txdot-urban-files-dgn-dwg.zip).

**Comment by ctrepka** [comment]
Not sure what y'all think, but I was thinking of putting this in the FAQ section at /help when we write that up. Then I'll do the walk-through-guide with intro.js and show the user the faq with this accordion open saying something like "This is the FAQ section. Check here if you have any questions you want quick answers to. If the answer isn't here, feel free to contact us below" then zoom to the General Contact Form.
