### ISSUE TITLE
Logo or Text?

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/dataHub#286]
Is it standard to have both (we don't for TWDB)? 
Could we just pick one?
This might be born from my hatred of the logo, but this is always bothered me. This is done on both DataHub and TNRIS.org

![TNRIS-Logo](https://user-images.githubusercontent.com/8459928/97579282-dd77dc80-19bf-11eb-8ab1-a1a9538e5d64.PNG)
![DataHub-Logo](https://user-images.githubusercontent.com/8459928/97579285-de107300-19bf-11eb-9444-ec9b3e9760cd.PNG)

**Comment by JasonKleinert** [comment]
I vote for text only, it has a cleaner look and matches the link to the water board site on the right side of the header.

**Comment by mitchellryant** [comment]
it could related to this https://github.com/TNRIS/tnris.org/issues/252
