### ISSUE TITLE
lidar note

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#34]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adambreznicky](https://github.com/adambreznicky)**
_Tuesday Jan 15, 2019 at 16:12 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/34_

----

remove list of tools:
"
LASTools provides a lossless compression of the data from las to laz formats.

Software with native LAZ support
ERDAS IMAGINE (14.1 and up) by Hexagon Geospatial
Global Mapper (13.1 and up) by Blue Marble Geo
ENVI LiDAR (5.1 and up) by Exelis VIS
FME (2012 and up) by Safe Software
LAStools by rapidlasso
plas.io 3D Web Viewer by Hobu Inc.
FUSION (3.40 and up) by Bob McGaughey of the USDA
Voyager (1.3 and up) by Voyager GIS
GRASS GIS (7.0 and up) by Open Source Geospatial Foundation (OSGeo)
"

also, note about the classifications existing in the project report

**Comment by adambreznicky** [comment]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwhaney](https://github.com/jwhaney)**
_Wednesday Jan 16, 2019 at 20:12 GMT_

----

i think you knocked this out yesterday @adambreznicky with commit 4507c13a830d0eeb9bb832c6a877357691523857. not sure about the note about classification?

**Comment by adambreznicky** [comment]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adambreznicky](https://github.com/adambreznicky)**
_Wednesday Jan 16, 2019 at 20:18 GMT_

----

i got rid of the software list but the lidar note still needs new, additional text about classifications existing in the project report. @gmullins and @ThorTheDestroyer can help determine how to say it. maybe...
"Vertical classifications can be found in the Project Report. Download the Project Report zipfile in the link below."

this is also under the assumption that every lidar dataset has a project report for download and their classifications are in it. let's get up with stratmap to verify all this.

**Comment by adambreznicky** [comment]
<a href="https://github.com/ThorTheDestroyer"><img src="https://avatars1.githubusercontent.com/u/8398036?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThorTheDestroyer](https://github.com/ThorTheDestroyer)**
_Wednesday Jan 16, 2019 at 20:45 GMT_

----

I had talked to Jason about this the other day.  The classifications are in almost all of the metadata; however I feel this would be best represented in the spec breakout field(resolution, agency, coverage extent, etc) along with the vertical accuracy of each dataset.  I feel the classification is a technical specification and belongs in a metadata field instead of in a paragraph that is a general descriptor about the project.

**Comment by adambreznicky** [comment]
<a href="https://github.com/adambreznicky"><img src="https://avatars3.githubusercontent.com/u/5650145?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adambreznicky](https://github.com/adambreznicky)**
_Wednesday Jan 16, 2019 at 20:57 GMT_

----

yes, we discussed this idea as metadata (which is correct) and there is an issue (#19) to adjust the schema for it in the future but schema changes are out of scope in this stage of the project. at a later date, we can make those database changes and, at that time, y'all will be able to go through and populate for it to show.

what we are discussing within this issue (#34) is how to note to users classification information in the mean time until we can get to that enhancement.

**Comment by adambreznicky** [comment]
<a href="https://github.com/ThorTheDestroyer"><img src="https://avatars1.githubusercontent.com/u/8398036?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ThorTheDestroyer](https://github.com/ThorTheDestroyer)**
_Wednesday Jan 16, 2019 at 21:25 GMT_

----

Sounds good, since we got a case of schema lock, putting them in the new description would be preferable since most people have a hard time reading and finding things in the metadata.  I'll be sure to go back and add those in.

**Comment by adambreznicky** [comment]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwhaney](https://github.com/jwhaney)**
_Tuesday Jan 22, 2019 at 17:13 GMT_

----

do we want to put a generic statement in the description across all lidar category datasets, something like "please see project report under supplemental downloads for classification information" ?? 
that way @ThorTheDestroyer / Stratmap doesn't have to go through each lidar dataset to find info and add to description manually in admin console.

**Comment by adambreznicky** [comment]
<a href="https://github.com/jwhaney"><img src="https://avatars1.githubusercontent.com/u/13525011?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwhaney](https://github.com/jwhaney)**
_Tuesday Jan 22, 2019 at 20:13 GMT_

----

talked to @ThorTheDestroyer and he is working on getting all the necessary lidar classification info for each specific lidar collection into the descriptions using the shared Excel online doc.

this issue is in progress, pending the finishing up of the updates to the descriptions.

**Comment by jwhaney** [comment]
@ThorTheDestroyer @gmullins @adambreznicky do we know where we stand on this issue? i'm going through and checking up on older issues to kind of see what the status is.

**Comment by gmullins** [comment]
@adambreznicky @jwhaney I think the list of classes should be in the Description on all lidar datasets. I found some with and without. @ThorTheDestroyer Can you please check through the lidar datasets and added classification info to each Description? Most recent ones are missing this. Thanks!! And then close this issue when done, ya?

**Comment by ThorTheDestroyer** [comment]
@gmullins Completed. 

@adambreznicky @jwhaney  please close the issue.
