### ISSUE TITLE
load web services in entry card

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/dataHub#95]
<a href="https://github.com/mitchellryant"><img src="https://avatars1.githubusercontent.com/u/8459928?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mitchellryant](https://github.com/mitchellryant)**
_Friday Feb 15, 2019 at 22:51 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/95_

----

From Richard: load web services in entry card.

Instead of an image(s) load a leaflet map with the services. User could pan\zoom interact with dataset.

**Comment by jwhaney** [comment]
@mitchellryant @adambreznicky is this issue related to the download collection details tab re-organization? in other words, we talked about bringing the download map into the main details tab and moving the images carousel to a images or preview tab (currently the download tab).

just wanted to check if we had an issue for that which maybe this one is or if i need to create a new issue. I've already started a feature branch to swap images and the download map.

**Comment by adambreznicky** [comment]
i believe this is separate from relocating the download map like we discussed.

i think this idea was, if a dataset has a wms service, to have an interactive map with the service as a layer for the user to view it in a live webmap. i would imagine it should be part of the wms service link partial since they are so related. but this idea came up before we decided to move the download map. the wms link partial shows on the details tab and it might be too much to have multiple maps on that tab. what do y'all think? maybe we should meet and discuss the ux/ui related to this idea?

i personally think that a wms service map is too much and unnecessary but i'd like to hear y'alls opinions

**Comment by jwhaney** [comment]
ok thanks for the clarification. i'll create a new issue for the download/images re-org.

ya im not sure how i feel about multiple maps on that main tab once we move over the download map. there is already a big button to send the user to a map showing the wms. i'm kinda on your side about just duplicating the same map inside the dataHub. seems unnecessary to me.

**Comment by JasonKleinert** [comment]
I agree that these are separate. We should all discuss the best implementation for this original issue , live preview.

**Comment by adambreznicky** [comment]
@jwhaney @JasonKleinert now that the historical aerials have an index download map, the wms service is loaded in the layer chooser as "PREVIEW". i'm thinking, maybe we should expand the download map to act the same way? if a wms service exists for a collection, have it added to the map as the "PREVIEW"? thoughts?

**Comment by JasonKleinert** [comment]
I think that sounds good. Would we want to make the preview tab with the image carousel go away then? I don't think it is necessary after we have a live preview feature.

**Comment by adambreznicky** [comment]
resolved via commit 2c27f0476d62a05db6ff4e08c5fbc785ca7e577b
